### PR TITLE
start with introduction

### PR DESCRIPTION
**Pull request by jensgerlach**
Could you please have look at my initial attempts.
I hope I did not misunderstand your french.
I would also like to know whether you consider my translation as to free.

### CODE REVIEW

**Comment by jensgerlach** [comment]
I have updated the introduction in the meantime.

**Comment by AllanBlanchard** [comment]
Apparently you modified the file :
french > instructions-basiques-et-structures-de-controle > introduction.md

instead of :
english > basic-instructions-and-control-structures > introduction.md

I think I could modify your commit to integrate it but then it would cause conflict in case you want to update your fork from mine. So I prefer to let you mv the files yourself. 

Except this, the translation is fine (I will translate the remaining expression and the few typos myself).

Thanks a lot.

**Comment by jensgerlach** [comment]
Ah, that was stupid of me to work in the French directory …
Sorry.
I will fix this and create a new merge request.

Jens

**Comment by AllanBlanchard** [comment]
Well, that's not that bad since I just realize that the french content in the "english" directory has not been updated to the last version. So you used the right one.

I updated the different files in this chapter with the last version of the french files.

**Comment by jensgerlach** [comment]
So, I moved my translation in subdirectory "english" and reverted the corresponding file in the "french" subdirectory.
Before, however I had synchronised my fork with your upstream.
Hope everything is right now.

**Pull request merged**
